language: java
jdk: openjdk9
before_script: chmod +x gradlew
jobs:
  include:
  - stage: build
    script: "./gradlew clean warNoStatic warCopy zipStatic artifactsCopy"
  - stage: test
    script: "./gradlew test"
  - stage: deploy -test
    script: "./deploy.sh"
  - stage: deploy -staging
    script: "./deploy.sh"
  - stage: deploy -prod
    script: "./deploy.sh"
